### ISSUE TITLE
Too many requests. Please try again.(react-native)

### ISSUE THREAD

**Issue by sanjaysoalnki2000** [PhonePe/pg-sdk-react-native-sample#11]
`{"error": "key_error_code:ERROR_B2B_API_RETURNED_ERRORkey_error_result:{\"success\":false,\"code\":\"TOO_MANY_REQUESTS\",\"message\":\"Too many requests. Please try again.\",\"data\":{}}", "status": "FAILURE"}`

**Comment by NitinVermaPpe** [comment]
hey, are you still facing this?
