### ISSUE TITLE
getting Transaction status as SUCCESS but transaction is failing 

### ISSUE THREAD

**Issue by Tushar-Sartia** [PhonePe/pg-sdk-react-native-sample#12]
For this payload UPI payment method is not working and when we are doing the payment though card the payment is failing but we are getting transaction status as SUCCESS  
{
      merchantId: merchantId,
      merchantTransactionId: 'MT' + transactionId,
      merchantUserId: 'MUID' + merchantUId,
      amount: amount * 100,
      redirectUrl: 'https://webhook.site/redirect-url',
      redirectMode: 'REDIRECT',
      callbackUrl: 'https://webhook.site/callback-url',
      mobileNumber: '9999999999',
      paymentInstrument: {
        type: 'PAY_PAGE',
      },
    };

**Comment by NitinVermaPpe** [comment]
hey, are you still facing this?

please explain your issue in detail... please also attach a video so that we can have a look at the issue.

**Comment by Tushar-Sartia** [comment]
{
merchantId: merchantId,
merchantTransactionId: 'MT' + transactionId,
merchantUserId: 'MUID' + merchantUId,
amount: amount * 100,
redirectUrl: 'https://webhook.site/redirect-url',
redirectMode: 'REDIRECT',
callbackUrl: 'https://webhook.site/callback-url',
mobileNumber: '9999999999',
paymentInstrument: {
type: 'PAY_PAGE',
},
}; 
For this payload in react native app, when I was doing the payment it was giving the response as {"status": "SUCCESS"}, and this response we are getting for both , when payment is failing and payment is successful .
We must be getting the response as this 
{
    "merchantId":"PGTESTPAYUAT",
    "merchantTransactionId":"M1710421776899",
    "transactionId":"T2403141839341827404399",
    "amount":100,
    "state":"COMPLETED",
    "responseCode":"SUCCESS",
    "paymentInstrument":{
        "type":"NETBANKING",
        "pgTransactionId":"1995464776",
        "pgServiceTransactionId":"PG22122916083344934300",
        "bankTransactionId":null,"bankId":"","arn":"12131261"
    }
} but I didn't get this response
I also checked the phonepe lib docs too, but was unable to resolve the issue so, I tried to implemented this using webview and it is working fine in webview no issue at all ..getting perfect response 
I don't have any videos right now , so won't be able to upload the video

**Comment by NitinVermaPpe** [comment]
SDK response just tells you if app flow got completed or not. it will not the tell you status of the transaction. You need to git status API for that. check "Step 4. Check the payment status" in [dev docs](https://developer.phonepe.com/v1/docs/react-native-sdk-integration-standard/)
Additionaly, this Payment Status API must be from your sever to ppe server.

As far as SDK is concerned, you will just know if payment got completed(failed/success) or it got cancelled (back press). This data is present in "STATUS" key in result.
