### ISSUE TITLE
how to add manually package in MainApplication.java

### ISSUE THREAD

**Issue by kukadiyaAni** [PhonePe/pg-sdk-react-native-sample#13]
I have an old version of react-native and I need to manually link Phonepe SDK, after installed I tried to add PhonePackahge in MainApplication.java file but it's not import

Can you help me out with this so, I can process ahead, without manually link I run the application then get the error init method null not found error

**Comment by Tushar-Sartia** [comment]
You don't need to add anything in the MainApplication.java file .

Follow this : https://developer.phonepe.com/v1/docs/reactnative-sdk-integration for the proper implementation
