### ISSUE TITLE
BAD_REQUEST : Please check the input you have provided

### ISSUE THREAD

**Issue by Ajay-Origin** [PhonePe/pg-sdk-react-native-sample#14]
using the below payload I created checksum. I didn't get 401 that means checksum is correct, then why this error?

{
  "merchantId": "MERCHANTUAT",
  "merchantUserId": "08ebd562-9fce-4a61-8d8b-798a982f0",
  "merchantTransactionId": "960a1dab767c4b7bbfb7c3b23bfd8f58",
  "amount": "52000",
  "mobileNumber": "9812345678",
  "callbackUrl": "https://webhook.com/ourhandler",
  "paymentInstrument": {
    "type": "UPI_INTENT",
    "targetApp": "com.phonepe.app"
  },
  "deviceContext": {
    "deviceOS": "ANDROID"
  }
}

![image](https://github.com/PhonePe/pg-sdk-react-native-sample/assets/87091017/c50cc08d-a4cb-43a8-bff2-e71551b6a081)

I am using your Git hub app to test if out payload and checksum are working or not, with SANDBOX selected in dropdown and MERCHANTUAT as merchant id.

**Comment by NitinVermaPpe** [comment]
hey, are you still facing this?

**Comment by Ajay-Origin** [comment]
The resolution is that first of all we should run the app on real device instead of testing on emulator. while you are testing it on the emulator you should paste checksum and body manually in the fields. Do the same for production testing too.

**Comment by Ajay-Origin** [comment]
closing it.
