### ISSUE TITLE
Cannot install node_modules

### ISSUE THREAD

**Issue by darshan-palm** [PhonePe/pg-sdk-react-native-sample#18]
Cannot install libraries, in npm it throws following error:
 EINTEGRITY
npm ERR! sha512-aUHe7TvYnwK47MEdwPT+y/qJbWn/EjfoETaJN7dxGCdTtrGrsX3F3IAQReDiv3glO2SUlyWxHB2MfNXYzkjXnw== integrity checksum failed when using sha512: wanted sha512-aUHe7TvYnwK47MEdwPT+y/qJbWn/EjfoETaJN7dxGCdTtrGrsX3F3IAQReDiv3glO2SUlyWxHB2MfNXYzkjXnw== but got sha512-+UUBtlnjJGGmdUQvZ1hcDnZRY/moqfgENRhNE6Z2CMnK97VWnM4wMDWyw1lkD1MB3IGXHVwXOOpbIuDXI+jiiQ==. (13404 bytes)

I am using command

npm i -f (as mentioned in Readme file)

**Comment by NitinVermaPpe** [comment]
closing this as it doesn't look like phonepe issue. 

try searching on google.
a quick search gave me this result: https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0
