### ISSUE TITLE
if npm i than  error  (not work npm i -f)

### ISSUE THREAD

**Issue by kartiknadcab** [PhonePe/pg-sdk-react-native-sample#19]
npm ERR! sha512-aUHe7TvYnwK47MEdwPT+y/qJbWn/EjfoETaJN7dxGCdTtrGrsX3F3IAQReDiv3glO2SUlyWxHB2MfNXYzkjXnw== integrity checksum failed when using sha512: wanted sha512-anw== but got sha512-+UUBtlnjJGGmdUQvZ1hcDnZRY/moqfgENRhNE6Z2CMnK97VWnM4wMDWyw1lkD1MB3IGXHVwXOOpbIuDXI+jiiQ==. (13404 bytes)

**Comment by NitinVermaPpe** [comment]
dulicate of https://github.com/PhonePe/pg-sdk-react-native-sample/issues/18
