### ISSUE TITLE
UPI payment button not working and also card payment not working

### ISSUE THREAD

**Issue by sangram-samanta** [PhonePe/pg-sdk-react-native-sample#20]
https://github.com/PhonePe/pg-sdk-react-native-sample/assets/90088705/cedc82a8-01af-4ffd-bac0-cc46a559463d

**Comment by NitinVermaPpe** [comment]
this github repo is only a demo app which shows how to integrate payment flow in rn.

for any issue related to the actual payment:
1. double verify your code
2. else react out to [merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com)
