### ISSUE TITLE
Too many requests. Please try again

### ISSUE THREAD

**Issue by sangram37** [PhonePe/pg-sdk-react-native-sample#21]
`import { Pressable, StyleSheet, Text, View } from 'react-native'
import React from 'react'
import PhonePePaymentSDK from 'react-native-phonepe-pg' 
import { sha256 } from 'js-sha256'

const App = () => {
  const checkinit=()=>{

  PhonePePaymentSDK.init(
		'SANDBOX',
    'PGTESTPAYUAT',
    '',
    true
  	).then(result => {
  console.log(result)
	})
  }
  const pay=()=>{
    let x = {
      "merchantId": "PGTESTPAYUAT",
      "merchantTransactionId": new Date().getTime().toString(),
      "merchantUserId": new Date().getTime().toString()+'klm',
      "amount": 1000,
      "redirectUrl": "https://webhook.site/redirect-url",
      "redirectMode": "REDIRECT",
      "callbackUrl": "https://webhook.site/callback-url",
      "mobileNumber": "9999999999",
      "paymentInstrument": {
        "type": "PAY_PAGE"
      }
    }
    const utf8Str = JSON.stringify(x)
    const body=btoa(utf8Str)
    const checkSum=sha256(`${body} /pg/v1/pay099eb0cd-02cf-4e2a-8aca-3e6c6aff0399`)+ '###' + 1

    
    PhonePePaymentSDK.startTransaction(body, checkSum, null, null).then( a => { console.log(a) })
  }
  return (
    <View style={{flex:1}}>
      <Pressable style={{backgroundColor:'red',width:200,height:80,alignItems:'center',alignSelf:'center',justifyContent:'center'}} onPress={checkinit}>
      <Text>init</Text>
      </Pressable>
      <Pressable style={{backgroundColor:'green',width:200,height:80,alignItems:'center',alignSelf:'center',justifyContent:'center'}} onPress={pay}>
      <Text>pay</Text>
      </Pressable>
    </View>
  )
}

export default App

const styles = StyleSheet.create({})`       

Error
{"error": "key_error_code:ERROR_B2B_API_RETURNED_ERRORkey_error_result:{\"success\":false,\"code\":\"TOO_MANY_REQUESTS\",\"message\":\"Too many requests. Please try again.\",\"data\":{}}", "status": "FAILURE"}

**Comment by NitinVermaPpe** [comment]
hi, please reach out to [merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com)

**Comment by sangram37** [comment]
I have not got any response from this email. how you can close the issue without resolve.Please reply. Your test credential is not working as well.

**Comment by NitinVermaPpe** [comment]
hi Sangram, I have only closed it as Not Planned/ Won't fix. your actual issue resolution will happen over email.

Github issues is not the correct place to raise such kind of issues.

if you are getting any kind of error, send an email > kindly wait for few hours.

if you don't get response over email, bump it

**Comment by sangram37** [comment]
Here's a polished version of your message:

Hi NitinVermaPpe,

I have not received any response from this email in the last two weeks. Additionally, my issue has not been resolved, and the test card details you provided are not working. Could you please provide some guidance on what to do next?

**Comment by NitinVermaPpe** [comment]
oh, I will escalate it internally.
please share the email subject with which you initiated the email

**Comment by sangram37** [comment]
Urgent: Payment Gateway Issues - UPI and Card Payments Not Working

**Comment by NitinVermaPpe** [comment]
cool, checking it internally

**Comment by NitinVermaPpe** [comment]
I hope that a call is scheduled with you? @sangram37
