### ISSUE TITLE
Please add an example that explains how to launch a Payment app on Clients Phone

### ISSUE THREAD

**Issue by sankparatkar** [PhonePe/pg-sdk-react-native-sample#22]
The [documentation ](https://developer.phonepe.com/v1/docs/react-native-sdk-integration-standard) does not explain how to help user open a specific UPI app to process the payment. Please advise.

**Comment by ajaym1056** [comment]
you not provided proper guidance for react native 
if I used testing mode giving 429 error for startPG transaction method

**Comment by NitinVermaPpe** [comment]
@ajaym1056 didnt get you
are you getting 429 error from SDK? If yes then this is not the correct place to raise it.

please reach out to email mentioned in the readme.

closing this issue as "sankparatkar" issue is resolved

**Comment by sankparatkar** [comment]
@NitinVermaPpe  Sorry, it doesn't work 

` const result = await PhonePePaymentSDK.startTransaction(body, checksum, "com.google.android.apps.nbu.paisa.user", "")`
 
 opens up the standard checkout page
 
Do we have to pass the app name in the PAY_API call as well?
https://developer.phonepe.com/v1/reference/pay-api-1/ only suggest way to pass instrument type as PAY_PAGE

> Payment instrument type.
> Value will be: PAY_PAGE

**Comment by NitinVermaPpe** [comment]
hey @sankparatkar , I just got to know from team that If you want to do custom integration (like opening an app directly) then you will have to reach out to [merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com).

What you are referring to is standard checkout.

This is how you can choose bw custom and standard integration:
1. custom integration: If your app has it's own checkout page and you wish to handle the complete UI. (reach out to integration team for this)
2. standard integration: If you don't have/want to make any checkout/payment page in the app. (public docs available for this)

I'm sorry for the confusion.
