### ISSUE TITLE
Bitcode AppstoreConnect Submit Issue (Xcode 16.0)

### ISSUE THREAD

**Issue by Gyanprakash73** [PhonePe/pg-sdk-react-native-sample#24]
* Asset validation failed
Invalid Executable. The executable 'balert.app/Frameworks/PhonePePayment.framework/ PhonePePayment' contains bitcode. (ID: 03380d1e-b524-4654-b1f3-49900fd2976a)

![error-iphone](https://github.com/user-attachments/assets/c9c6aaf5-ca47-4850-b6dc-796756996554)

**I am facing the above error while Distribute App on App Store Connect.**

**Explanation** : According to my understanding in Xcode 16 not include bitcode and PhonePe Payment SDK Version 2.0.1 included bitcode that's the issue.

**Comment by rajanarora27** [comment]
Hi, Will release the new version and fix this issue

**Comment by Gyanprakash73** [comment]
> Hi, Will release the new version and fix this issue

Ok, Can you tell me when it will come or for now any alternative way to remove the bitcode from exiting SDK v2.0.1

**Comment by rajanarora27** [comment]
Will try to fix this at the end of next week. No, Alternate way on the App side.
