### ISSUE TITLE
Could not determine the dependencies of task ':phonepe-payment-sdk:compileDebugAidl'.

### ISSUE THREAD

**Issue by bibekk-mss** [PhonePe/pg-sdk-react-native-sample#4]
npx react-native run-android
info JS server already running.
info Installing the app...

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.3.1
Gradle: 7.5.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the 
Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 5 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: 
https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':phonepe-payment-sdk:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':phonepe-payment-sdk:debugCompileClasspath'.
   > Could not find phonepe.intentsdk.android.release:IntentSDK:2.1.1.
     Required by:
         project :phonepe-payment-sdk

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an 
exception. * What went wrong: Could not determine the dependencies of task ':phonepe-payment-sdk:compileDebugAidl'. > Could not resolve all task dependencies for configuration ':phonepe-payment-sdk:debugCompileClasspath'. > Could not find phonepe.intentsdk.android.release:IntentSDK:2.1.1. Required by: project :phonepe-payment-sdk * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 24s.
info Run CLI with --verbose flag for more details.

**Comment by AnshumanPhonePe** [comment]
As we can see in your error log: Could not find phonepe.intentsdk.android.release:IntentSDK:2.1.1.
You haven't added PhonePe Maven Repository link which is mentioned in [PhonePe developer docs](https://developer.phonepe.com/v1/docs/reactnative-sdk-integration#android)
Please, follow mentioned steps in above document.
