### ISSUE TITLE
Could not resolve project :react-native-phonepe-pg.

### ISSUE THREAD

**Issue by sanjaysoalnki2000** [PhonePe/pg-sdk-react-native-sample#9]
"react-native": "0.64.4"

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-phonepe-pg.
     Required by:
         project :app
      > No matching configuration of project :react-native-phonepe-pg was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.
          
          
          
  `allprojects {
       repositories {

        google()  // Google's Maven repository
        mavenLocal()
        maven {
            url  "https://phonepe.mycloudrepo.io/public/repositories/phonepe-intentsdk-android"
        }`

**Comment by NitinVermaPpe** [comment]
please follow https://developer.phonepe.com/v1/docs/react-native-sdk-integration-standard
